[workspace]
members = ["src/app"]
resolver = "3"

[workspace.dependencies]
# Local

# External
actix-web = "4.10"
anyhow = "1.0"
config = "0.15"
dotenv = "0.15"
leptos = { version = "0.7", features = ["ssr"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.44", features = ["rt", "macros"] }
